from __future__ import annotations

from dataclasses import dataclass, field, replace
from enum import Enum
from typing import Optional


class CardRarity(str, Enum):
    BASIC = "BASIC"
    COMMON = "COMMON"
    UNCOMMON = "UNCOMMON"
    RARE = "RARE"
    CURSE = "CURSE"
    SPECIAL = "SPECIAL"


class CardType(str, Enum):
    ATTACK = "ATTACK"
    SKILL = "SKILL"
    POWER = "POWER"
    STATUS = "STATUS"
    CURSE = "CURSE"


class CurseEffectType(str, Enum):
    NONE = "none"
    END_OF_TURN_DAMAGE = "end_of_turn_damage"
    END_OF_TURN_WEAK = "end_of_turn_weak"
    END_OF_TURN_VULNERABLE = "end_of_turn_vulnerable"
    END_OF_TURN_FRAIL = "end_of_turn_frail"
    ON_CARD_PLAYED_LOSE_HP = "on_card_played_lose_hp"
    LIMIT_CARDS_PER_TURN = "limit_cards_per_turn"
    IF_REMOVED_LOSE_MAX_HP = "if_removed_lose_max_hp"
    INNATE_COPY_AT_END = "innate_copy_at_end"
    REGRET_EFFECT = "regret_effect"
    CANNOT_REMOVE_FROM_DECK = "cannot_remove_from_deck"
    RETURN_TO_HAND_ON_EXHAUST = "return_to_hand_on_exhaust"
    VACUOUS = "vacuous"


@dataclass(frozen=True)
class CardDef:
    id: str
    rarity: CardRarity
    card_type: CardType = CardType.ATTACK
    base_damage: int = 0
    base_block: int = 0
    base_magic_number: int = 0
    cost: int = -1
    is_exhaust: bool = False
    is_ethereal: bool = False
    is_innate: bool = False
    is_retain: bool = False
    target_required: Optional[bool] = None
    is_unplayable: bool = False
    curse_effect_type: CurseEffectType = CurseEffectType.NONE
    curse_effect_value: int = 0
    upgrade_damage: int = 0
    upgrade_block: int = 0
    upgrade_magic_number: int = 0
    upgrade_cost: Optional[int] = None
    upgrade_exhaust: Optional[bool] = None
    upgrade_ethereal: Optional[bool] = None
    upgrade_innate: Optional[bool] = None
    upgrade_retain: Optional[bool] = None
    upgrade_description: Optional[str] = None
    name_cn: str = ""
    description: str = ""


# ---------------------------------------------------------------------------
# Complete Ironclad card table (from decompiled source)
# 3 BASIC + 20 COMMON + 34 UNCOMMON + 18 RARE = 75 total
# ---------------------------------------------------------------------------

IRONCLAD_ALL_DEFS: dict[str, CardDef] = {
    # --- BASIC (starters, not in reward pool) ---
    "Strike": CardDef("Strike", CardRarity.BASIC, CardType.ATTACK, name_cn="鎵撳嚮"),
    "Defend": CardDef("Defend", CardRarity.BASIC, CardType.SKILL, name_cn="闃插尽"),
    "Bash": CardDef("Bash", CardRarity.BASIC, CardType.ATTACK, name_cn="鐥涘嚮"),

    # --- COMMON (20) ---
    "Anger": CardDef("Anger", CardRarity.COMMON, CardType.ATTACK, name_cn="Anger"),
    "Armaments": CardDef("Armaments", CardRarity.COMMON, CardType.SKILL, name_cn="姝﹁"),
    "BodySlam": CardDef("BodySlam", CardRarity.COMMON, CardType.ATTACK, name_cn="鍏ㄨ韩鎾炲嚮"),
    "Clash": CardDef("Clash", CardRarity.COMMON, CardType.ATTACK, name_cn="浜ら攱"),
    "Cleave": CardDef("Cleave", CardRarity.COMMON, CardType.ATTACK, name_cn="Cleave"),
    "Clothesline": CardDef("Clothesline", CardRarity.COMMON, CardType.ATTACK, name_cn="Clothesline"),
    "Flex": CardDef("Flex", CardRarity.COMMON, CardType.SKILL, name_cn="娲诲姩鑲岃倝"),
    "Havoc": CardDef("Havoc", CardRarity.COMMON, CardType.SKILL, name_cn="鐮寸伃"),
    "Headbutt": CardDef("Headbutt", CardRarity.COMMON, CardType.ATTACK, name_cn="澶存"),
    "HeavyBlade": CardDef("HeavyBlade", CardRarity.COMMON, CardType.ATTACK, name_cn="閲嶅垉"),
    "IronWave": CardDef("IronWave", CardRarity.COMMON, CardType.ATTACK, name_cn="IronWave"),
    "PerfectedStrike": CardDef("PerfectedStrike", CardRarity.COMMON, CardType.ATTACK, name_cn="瀹岀編鎵撳嚮"),
    "PommelStrike": CardDef("PommelStrike", CardRarity.COMMON, CardType.ATTACK, name_cn="鍓戞焺鎵撳嚮"),
    "ShrugItOff": CardDef("ShrugItOff", CardRarity.COMMON, CardType.SKILL, name_cn="鑰歌偐鏃犺"),
    "SwordBoomerang": CardDef("SwordBoomerang", CardRarity.COMMON, CardType.ATTACK, name_cn="SwordBoomerang"),
    "Thunderclap": CardDef("Thunderclap", CardRarity.COMMON, CardType.ATTACK, name_cn="闂數闇归洺"),
    "TrueGrit": CardDef("TrueGrit", CardRarity.COMMON, CardType.SKILL, name_cn="鍧氭瘏"),
    "TwinStrike": CardDef("TwinStrike", CardRarity.COMMON, CardType.ATTACK, name_cn="鍙岄噸鎵撳嚮"),
    "Warcry": CardDef("Warcry", CardRarity.COMMON, CardType.SKILL, is_exhaust=True, name_cn="鎴樺惣"),
    "WildStrike": CardDef("WildStrike", CardRarity.COMMON, CardType.ATTACK, name_cn="鐙傞噹鎵撳嚮"),

    # --- UNCOMMON (34) ---
    "BattleTrance": CardDef("BattleTrance", CardRarity.UNCOMMON, CardType.SKILL, name_cn="鎴樻枟涓撴敞"),
    "BloodforBlood": CardDef("BloodforBlood", CardRarity.UNCOMMON, CardType.ATTACK, name_cn="浠ヨ杩樿"),
    "Bloodletting": CardDef("Bloodletting", CardRarity.UNCOMMON, CardType.SKILL, is_exhaust=True, name_cn="鏀捐"),
    "BurningPact": CardDef("BurningPact", CardRarity.UNCOMMON, CardType.SKILL, name_cn="鐕冪儳濂戠害"),
    "Carnage": CardDef("Carnage", CardRarity.UNCOMMON, CardType.ATTACK, is_exhaust=True, is_ethereal=True, name_cn="娈嬫潃"),
    "Combust": CardDef("Combust", CardRarity.UNCOMMON, CardType.POWER, name_cn="鐕冪儳"),
    "DarkEmbrace": CardDef("DarkEmbrace", CardRarity.UNCOMMON, CardType.POWER, name_cn="榛戞殫涔嬫嫢"),
    "Disarm": CardDef("Disarm", CardRarity.UNCOMMON, CardType.SKILL, is_exhaust=True, name_cn="缂存"),
    "Dropkick": CardDef("Dropkick", CardRarity.UNCOMMON, CardType.ATTACK, is_exhaust=True, name_cn="Dropkick"),
    "DualWield": CardDef("DualWield", CardRarity.UNCOMMON, CardType.SKILL, name_cn="鍙屾寔"),
    "Entrench": CardDef("Entrench", CardRarity.UNCOMMON, CardType.SKILL, name_cn="宸╁浐"),
    "Evolve": CardDef("Evolve", CardRarity.UNCOMMON, CardType.POWER, name_cn="杩涘寲"),
    "FeelNoPain": CardDef("FeelNoPain", CardRarity.UNCOMMON, CardType.POWER, name_cn="鏃犳儳鐤肩棝"),
    "FireBreathing": CardDef("FireBreathing", CardRarity.UNCOMMON, CardType.POWER, name_cn="鐏劙鍚愭伅"),
    "FlameBarrier": CardDef("FlameBarrier", CardRarity.UNCOMMON, CardType.SKILL, name_cn="鐏劙灞忛殰"),
    "GhostlyArmor": CardDef("GhostlyArmor", CardRarity.UNCOMMON, CardType.SKILL, is_ethereal=True, name_cn="骞界伒閾犵敳"),
    "Hemokinesis": CardDef("Hemokinesis", CardRarity.UNCOMMON, CardType.ATTACK, name_cn="Hemokinesis"),
    "InfernalBlade": CardDef("InfernalBlade", CardRarity.UNCOMMON, CardType.SKILL, is_exhaust=True, name_cn="鍦扮嫳涔嬪垉"),
    "Inflame": CardDef("Inflame", CardRarity.UNCOMMON, CardType.POWER, name_cn="鐕冪儳"),
    "Intimidate": CardDef("Intimidate", CardRarity.UNCOMMON, CardType.SKILL, name_cn="濞佸悡"),
    "Metallicize": CardDef("Metallicize", CardRarity.UNCOMMON, CardType.POWER, name_cn="Metallicize"),
    "PowerThrough": CardDef("PowerThrough", CardRarity.UNCOMMON, CardType.SKILL, name_cn="纭拺"),
    "Pummel": CardDef("Pummel", CardRarity.UNCOMMON, CardType.ATTACK, name_cn="Pummel"),
    "Rage": CardDef("Rage", CardRarity.UNCOMMON, CardType.SKILL, name_cn="Rage"),
    "Rampage": CardDef("Rampage", CardRarity.UNCOMMON, CardType.ATTACK, name_cn="鏆磋蛋"),
    "RecklessCharge": CardDef("RecklessCharge", CardRarity.UNCOMMON, CardType.ATTACK, name_cn="鏃犺皨鍐查攱"),
    "Rupture": CardDef("Rupture", CardRarity.UNCOMMON, CardType.POWER, name_cn="鎾曡"),
    "SearingBlow": CardDef("SearingBlow", CardRarity.UNCOMMON, CardType.ATTACK, name_cn="鐏肩儹鏀诲嚮"),
    "SecondWind": CardDef("SecondWind", CardRarity.UNCOMMON, CardType.SKILL, name_cn="閲嶆尟绮剧"),
    "SeeingRed": CardDef("SeeingRed", CardRarity.UNCOMMON, CardType.SKILL, is_exhaust=True, name_cn="SeeingRed"),
    "Sentinel": CardDef("Sentinel", CardRarity.UNCOMMON, CardType.SKILL, is_exhaust=True, name_cn="鍝ㄥ叺"),
    "SeverSoul": CardDef("SeverSoul", CardRarity.UNCOMMON, CardType.ATTACK, is_exhaust=True, name_cn="SeverSoul"),
    "Shockwave": CardDef("Shockwave", CardRarity.UNCOMMON, CardType.SKILL, name_cn="Shockwave"),
    "SpotWeakness": CardDef("SpotWeakness", CardRarity.UNCOMMON, CardType.SKILL, name_cn="瑙傚療寮辩偣"),

    # --- RARE (18) ---
    "Barricade": CardDef("Barricade", CardRarity.RARE, CardType.POWER, name_cn="澹佸瀿"),
    "Berserk": CardDef("Berserk", CardRarity.RARE, CardType.POWER, name_cn="鐙傛毚"),
    "Bludgeon": CardDef("Bludgeon", CardRarity.RARE, CardType.ATTACK, name_cn="閲嶉敜"),
    "Brutality": CardDef("Brutality", CardRarity.RARE, CardType.POWER, upgrade_innate=True, name_cn="娈嬫毚"),
    "Corruption": CardDef("Corruption", CardRarity.RARE, CardType.POWER, name_cn="鑵愬寲"),
    "DemonForm": CardDef("DemonForm", CardRarity.RARE, CardType.POWER, name_cn="DemonForm"),
    "DoubleTap": CardDef("DoubleTap", CardRarity.RARE, CardType.SKILL, name_cn="鍙屽彂"),
    "Exhume": CardDef("Exhume", CardRarity.RARE, CardType.SKILL, is_exhaust=True, name_cn="鍙戞帢"),
    "Feed": CardDef("Feed", CardRarity.RARE, CardType.ATTACK, name_cn="鐙傚"),
    "FiendFire": CardDef("FiendFire", CardRarity.RARE, CardType.ATTACK, is_exhaust=True, name_cn="鎭堕瓟涔嬬劙"),
    "Immolate": CardDef("Immolate", CardRarity.RARE, CardType.ATTACK, is_exhaust=True, name_cn="鐕旂キ"),
    "Impervious": CardDef("Impervious", CardRarity.RARE, CardType.SKILL, is_exhaust=True, name_cn="宀跨劧涓嶅姩"),
    "Juggernaut": CardDef("Juggernaut", CardRarity.RARE, CardType.POWER, name_cn="鍔夸笉鍙綋"),
    "LimitBreak": CardDef("LimitBreak", CardRarity.RARE, CardType.SKILL, name_cn="绐佺牬鏋侀檺"),
    "Offering": CardDef("Offering", CardRarity.RARE, CardType.SKILL, is_exhaust=True, name_cn="绁搧"),
    "Reaper": CardDef("Reaper", CardRarity.RARE, CardType.ATTACK, is_exhaust=True, name_cn="姝讳骸鏀跺壊"),
    "Uppercut": CardDef("Uppercut", CardRarity.UNCOMMON, CardType.ATTACK, name_cn="Uppercut"),
    "Whirlwind": CardDef("Whirlwind", CardRarity.UNCOMMON, CardType.ATTACK, name_cn="Whirlwind"),
    # Duplicate key override to keep rare-card metadata in sync with runtime behavior.
    "Feed": CardDef("Feed", CardRarity.RARE, CardType.ATTACK, is_exhaust=True, name_cn="Feed"),
}

def _watcher_card(
    card_id: str,
    rarity: CardRarity,
    card_type: CardType,
    cost: int,
    *,
    base_damage: int = 0,
    base_block: int = 0,
    base_magic_number: int = 0,
    is_exhaust: bool = False,
    is_ethereal: bool = False,
    is_innate: bool = False,
    is_retain: bool = False,
    is_unplayable: bool = False,
    upgrade_damage: int = 0,
    upgrade_block: int = 0,
    upgrade_magic_number: int = 0,
    upgrade_cost: Optional[int] = None,
    upgrade_ethereal: Optional[bool] = None,
    upgrade_innate: Optional[bool] = None,
    upgrade_retain: Optional[bool] = None,
) -> CardDef:
    return CardDef(
        id=card_id,
        rarity=rarity,
        card_type=card_type,
        base_damage=base_damage,
        base_block=base_block,
        base_magic_number=base_magic_number,
        cost=cost,
        is_exhaust=is_exhaust,
        is_ethereal=is_ethereal,
        is_innate=is_innate,
        is_retain=is_retain,
        is_unplayable=is_unplayable,
        upgrade_damage=upgrade_damage,
        upgrade_block=upgrade_block,
        upgrade_magic_number=upgrade_magic_number,
        upgrade_cost=upgrade_cost,
        upgrade_ethereal=upgrade_ethereal,
        upgrade_innate=upgrade_innate,
        upgrade_retain=upgrade_retain,
    )


WATCHER_ALL_DEFS: dict[str, CardDef] = {
    "Strike_P": _watcher_card("Strike_P", CardRarity.BASIC, CardType.ATTACK, 1, base_damage=6, upgrade_damage=3),
    "Defend_P": _watcher_card("Defend_P", CardRarity.BASIC, CardType.SKILL, 1, base_block=5, upgrade_block=3),
    "Eruption": _watcher_card("Eruption", CardRarity.BASIC, CardType.ATTACK, 2, base_damage=9, upgrade_cost=1),
    "Vigilance": _watcher_card("Vigilance", CardRarity.BASIC, CardType.SKILL, 2, base_block=8, upgrade_block=4),
    "BowlingBash": _watcher_card("BowlingBash", CardRarity.COMMON, CardType.ATTACK, 1, base_damage=7, upgrade_damage=3),
    "Consecrate": _watcher_card("Consecrate", CardRarity.COMMON, CardType.ATTACK, 0, base_damage=5, upgrade_damage=3),
    "Crescendo": _watcher_card("Crescendo", CardRarity.COMMON, CardType.SKILL, 1, is_exhaust=True, is_retain=True, upgrade_cost=0),
    "CrushJoints": _watcher_card("CrushJoints", CardRarity.COMMON, CardType.ATTACK, 1, base_damage=8, base_magic_number=1, upgrade_damage=2, upgrade_magic_number=1),
    "CutThroughFate": _watcher_card("CutThroughFate", CardRarity.COMMON, CardType.ATTACK, 1, base_damage=7, base_magic_number=2, upgrade_damage=2, upgrade_magic_number=1),
    "EmptyBody": _watcher_card("EmptyBody", CardRarity.COMMON, CardType.SKILL, 1, base_block=7, upgrade_block=3),
    "EmptyFist": _watcher_card("EmptyFist", CardRarity.COMMON, CardType.ATTACK, 1, base_damage=9, upgrade_damage=5),
    "Evaluate": _watcher_card("Evaluate", CardRarity.COMMON, CardType.SKILL, 1, base_block=6, upgrade_block=4),
    "FlurryOfBlows": _watcher_card("FlurryOfBlows", CardRarity.COMMON, CardType.ATTACK, 0, base_damage=4, upgrade_damage=2),
    "FlyingSleeves": _watcher_card("FlyingSleeves", CardRarity.COMMON, CardType.ATTACK, 1, base_damage=4, is_retain=True, upgrade_damage=2),
    "FollowUp": _watcher_card("FollowUp", CardRarity.COMMON, CardType.ATTACK, 1, base_damage=7, upgrade_damage=4),
    "Halt": _watcher_card("Halt", CardRarity.COMMON, CardType.SKILL, 0, base_block=3, base_magic_number=9, upgrade_block=1),
    "JustLucky": _watcher_card("JustLucky", CardRarity.COMMON, CardType.ATTACK, 0, base_damage=3, base_block=2, base_magic_number=1, upgrade_damage=1, upgrade_block=1, upgrade_magic_number=1),
    "PressurePoints": _watcher_card("PressurePoints", CardRarity.COMMON, CardType.SKILL, 1, base_magic_number=8, upgrade_magic_number=3),
    "Prostrate": _watcher_card("Prostrate", CardRarity.COMMON, CardType.SKILL, 0, base_block=4, base_magic_number=2, upgrade_magic_number=1),
    "Protect": _watcher_card("Protect", CardRarity.COMMON, CardType.SKILL, 2, base_block=12, is_retain=True, upgrade_block=4),
    "SashWhip": _watcher_card("SashWhip", CardRarity.COMMON, CardType.ATTACK, 1, base_damage=8, base_magic_number=1, upgrade_damage=2, upgrade_magic_number=1),
    "ThirdEye": _watcher_card("ThirdEye", CardRarity.COMMON, CardType.SKILL, 1, base_block=7, base_magic_number=3, upgrade_block=2, upgrade_magic_number=2),
    "Tranquility": _watcher_card("Tranquility", CardRarity.COMMON, CardType.SKILL, 1, is_exhaust=True, is_retain=True, upgrade_cost=0),
    "BattleHymn": _watcher_card("BattleHymn", CardRarity.UNCOMMON, CardType.POWER, 1, base_magic_number=1),
    "CarveReality": _watcher_card("CarveReality", CardRarity.UNCOMMON, CardType.ATTACK, 1, base_damage=6, upgrade_damage=4),
    "Collect": _watcher_card("Collect", CardRarity.UNCOMMON, CardType.SKILL, -1, is_exhaust=True),
    "Conclude": _watcher_card("Conclude", CardRarity.UNCOMMON, CardType.ATTACK, 1, base_damage=12, upgrade_damage=4),
    "DeceiveReality": _watcher_card("DeceiveReality", CardRarity.UNCOMMON, CardType.SKILL, 1, base_block=4, upgrade_block=3),
    "EmptyMind": _watcher_card("EmptyMind", CardRarity.UNCOMMON, CardType.SKILL, 1, base_magic_number=2, upgrade_magic_number=1),
    "Fasting": _watcher_card("Fasting", CardRarity.UNCOMMON, CardType.POWER, 2, base_magic_number=3, upgrade_magic_number=1),
    "FearNoEvil": _watcher_card("FearNoEvil", CardRarity.UNCOMMON, CardType.ATTACK, 1, base_damage=8, upgrade_damage=3),
    "ForeignInfluence": _watcher_card("ForeignInfluence", CardRarity.UNCOMMON, CardType.SKILL, 0, is_exhaust=True),
    "Foresight": _watcher_card("Foresight", CardRarity.UNCOMMON, CardType.POWER, 1, base_magic_number=3, upgrade_magic_number=1),
    "Indignation": _watcher_card("Indignation", CardRarity.UNCOMMON, CardType.SKILL, 1, base_magic_number=3, upgrade_magic_number=2),
    "InnerPeace": _watcher_card("InnerPeace", CardRarity.UNCOMMON, CardType.SKILL, 1, base_magic_number=3, upgrade_magic_number=1),
    "LikeWater": _watcher_card("LikeWater", CardRarity.UNCOMMON, CardType.POWER, 1, base_magic_number=5, upgrade_magic_number=2),
    "Meditate": _watcher_card("Meditate", CardRarity.UNCOMMON, CardType.SKILL, 1, base_magic_number=1, upgrade_magic_number=1),
    "MentalFortress": _watcher_card("MentalFortress", CardRarity.UNCOMMON, CardType.POWER, 1, base_magic_number=4, upgrade_magic_number=2),
    "Nirvana": _watcher_card("Nirvana", CardRarity.UNCOMMON, CardType.POWER, 1, base_magic_number=3, upgrade_magic_number=1),
    "Perseverance": _watcher_card("Perseverance", CardRarity.UNCOMMON, CardType.SKILL, 1, base_block=5, base_magic_number=2, is_retain=True, upgrade_block=2, upgrade_magic_number=1),
    "Pray": _watcher_card("Pray", CardRarity.UNCOMMON, CardType.SKILL, 1, base_magic_number=3, upgrade_magic_number=1),
    "ReachHeaven": _watcher_card("ReachHeaven", CardRarity.UNCOMMON, CardType.ATTACK, 2, base_damage=10, upgrade_damage=5),
    "Rushdown": _watcher_card("Rushdown", CardRarity.UNCOMMON, CardType.POWER, 1, base_magic_number=2, upgrade_cost=0),
    "Sanctity": _watcher_card("Sanctity", CardRarity.UNCOMMON, CardType.SKILL, 1, base_block=6, base_magic_number=2, upgrade_block=3),
    "SandsOfTime": _watcher_card("SandsOfTime", CardRarity.UNCOMMON, CardType.ATTACK, 4, base_damage=20, is_retain=True, upgrade_damage=6),
    "SignatureMove": _watcher_card("SignatureMove", CardRarity.UNCOMMON, CardType.ATTACK, 2, base_damage=30, upgrade_damage=10),
    "SimmeringFury": _watcher_card("SimmeringFury", CardRarity.UNCOMMON, CardType.SKILL, 1, base_magic_number=2, upgrade_magic_number=1),
    "Study": _watcher_card("Study", CardRarity.UNCOMMON, CardType.POWER, 2, base_magic_number=1, upgrade_cost=1),
    "Swivel": _watcher_card("Swivel", CardRarity.UNCOMMON, CardType.SKILL, 2, base_block=8, base_magic_number=8, upgrade_block=3),
    "TalkToTheHand": _watcher_card("TalkToTheHand", CardRarity.UNCOMMON, CardType.ATTACK, 1, base_damage=5, base_magic_number=2, is_exhaust=True, upgrade_damage=2, upgrade_magic_number=1),
    "Tantrum": _watcher_card("Tantrum", CardRarity.UNCOMMON, CardType.ATTACK, 1, base_damage=3, base_magic_number=3, upgrade_magic_number=1),
    "Wallop": _watcher_card("Wallop", CardRarity.UNCOMMON, CardType.ATTACK, 2, base_damage=9, upgrade_damage=3),
    "WaveOfTheHand": _watcher_card("WaveOfTheHand", CardRarity.UNCOMMON, CardType.SKILL, 1, base_magic_number=1, upgrade_magic_number=1),
    "Weave": _watcher_card("Weave", CardRarity.UNCOMMON, CardType.ATTACK, 0, base_damage=4, upgrade_damage=2),
    "WheelKick": _watcher_card("WheelKick", CardRarity.UNCOMMON, CardType.ATTACK, 2, base_damage=15, base_magic_number=2, upgrade_damage=5),
    "WindmillStrike": _watcher_card("WindmillStrike", CardRarity.UNCOMMON, CardType.ATTACK, 2, base_damage=7, base_magic_number=4, is_retain=True, upgrade_damage=3, upgrade_magic_number=1),
    "Worship": _watcher_card("Worship", CardRarity.UNCOMMON, CardType.SKILL, 2, base_magic_number=5),
    "WreathOfFlame": _watcher_card("WreathOfFlame", CardRarity.UNCOMMON, CardType.SKILL, 1, base_magic_number=5, upgrade_magic_number=3),
    "Alpha": _watcher_card("Alpha", CardRarity.RARE, CardType.SKILL, 1, is_exhaust=True, upgrade_innate=True),
    "Blasphemy": _watcher_card("Blasphemy", CardRarity.RARE, CardType.SKILL, 1, is_exhaust=True, upgrade_retain=True),
    "Brilliance": _watcher_card("Brilliance", CardRarity.RARE, CardType.ATTACK, 1, base_damage=12, upgrade_damage=4),
    "ConjureBlade": _watcher_card("ConjureBlade", CardRarity.RARE, CardType.SKILL, -1, is_exhaust=True),
    "DeusExMachina": _watcher_card("DeusExMachina", CardRarity.RARE, CardType.SKILL, -2, base_magic_number=2, is_exhaust=True, is_unplayable=True, upgrade_magic_number=1),
    "DevaForm": _watcher_card("DevaForm", CardRarity.RARE, CardType.POWER, 3, base_magic_number=1, is_ethereal=True, upgrade_ethereal=False),
    "Devotion": _watcher_card("Devotion", CardRarity.RARE, CardType.POWER, 1, base_magic_number=2, upgrade_magic_number=1),
    "Discipline": _watcher_card("Discipline", CardRarity.RARE, CardType.POWER, 2, upgrade_cost=1),
    "Establishment": _watcher_card("Establishment", CardRarity.RARE, CardType.POWER, 1, base_magic_number=1),
    "Judgement": _watcher_card("Judgement", CardRarity.RARE, CardType.SKILL, 1, base_magic_number=30, upgrade_magic_number=10),
    "LessonLearned": _watcher_card("LessonLearned", CardRarity.RARE, CardType.ATTACK, 2, base_damage=10, is_exhaust=True, upgrade_damage=3),
    "MasterReality": _watcher_card("MasterReality", CardRarity.RARE, CardType.POWER, 1, upgrade_cost=0),
    "Omniscience": _watcher_card("Omniscience", CardRarity.RARE, CardType.SKILL, 4, base_magic_number=2, is_exhaust=True, upgrade_cost=3),
    "Ragnarok": _watcher_card("Ragnarok", CardRarity.RARE, CardType.ATTACK, 3, base_damage=5, base_magic_number=5, upgrade_damage=1, upgrade_magic_number=1),
    "Scrawl": _watcher_card("Scrawl", CardRarity.RARE, CardType.SKILL, 1, is_exhaust=True, upgrade_cost=0),
    "SpiritShield": _watcher_card("SpiritShield", CardRarity.RARE, CardType.SKILL, 2, base_magic_number=3, upgrade_magic_number=1),
    "Unraveling": _watcher_card("Unraveling", CardRarity.RARE, CardType.SKILL, 2, is_exhaust=True, upgrade_cost=1),
    "Vault": _watcher_card("Vault", CardRarity.RARE, CardType.SKILL, 3, is_exhaust=True, upgrade_cost=2),
    "Wish": _watcher_card("Wish", CardRarity.RARE, CardType.SKILL, 3, base_damage=3, base_block=6, base_magic_number=25, is_exhaust=True, upgrade_damage=1, upgrade_block=2, upgrade_magic_number=5),
}

IRONCLAD_CURSE_DEFS: dict[str, CardDef] = {
    "AscendersBane": CardDef(
        id="AscendersBane",
        rarity=CardRarity.CURSE,
        card_type=CardType.CURSE,
        is_unplayable=True,
        is_exhaust=False,
        curse_effect_type=CurseEffectType.VACUOUS,
        upgrade_description=None,
    ),
    "Clumsy": CardDef(
        id="Clumsy",
        rarity=CardRarity.CURSE,
        card_type=CardType.CURSE,
        is_unplayable=True,
        is_exhaust=False,
        curse_effect_type=CurseEffectType.VACUOUS,
        upgrade_description=None,
    ),
    "CurseOfTheBell": CardDef(
        id="CurseOfTheBell",
        rarity=CardRarity.CURSE,
        card_type=CardType.CURSE,
        is_unplayable=True,
        is_exhaust=False,
        curse_effect_type=CurseEffectType.CANNOT_REMOVE_FROM_DECK,
        upgrade_description=None,
    ),
    "Decay": CardDef(
        id="Decay",
        rarity=CardRarity.CURSE,
        card_type=CardType.CURSE,
        is_unplayable=True,
        is_exhaust=False,
        curse_effect_type=CurseEffectType.END_OF_TURN_DAMAGE,
        curse_effect_value=2,
        upgrade_description=None,
    ),
    "Doubt": CardDef(
        id="Doubt",
        rarity=CardRarity.CURSE,
        card_type=CardType.CURSE,
        is_unplayable=True,
        is_exhaust=False,
        curse_effect_type=CurseEffectType.END_OF_TURN_WEAK,
        curse_effect_value=1,
        upgrade_description=None,
    ),
    "Injury": CardDef(
        id="Injury",
        rarity=CardRarity.CURSE,
        card_type=CardType.CURSE,
        is_unplayable=True,
        is_exhaust=False,
        curse_effect_type=CurseEffectType.NONE,
        upgrade_description=None,
        name_cn="鍙椾激",
    ),
    "Necronomicurse": CardDef(
        id="Necronomicurse",
        rarity=CardRarity.CURSE,
        card_type=CardType.CURSE,
        is_unplayable=True,
        is_exhaust=False,
        curse_effect_type=CurseEffectType.RETURN_TO_HAND_ON_EXHAUST,
        upgrade_description=None,
    ),
    "Pain": CardDef(
        id="Pain",
        rarity=CardRarity.CURSE,
        card_type=CardType.CURSE,
        is_unplayable=True,
        is_exhaust=False,
        curse_effect_type=CurseEffectType.ON_CARD_PLAYED_LOSE_HP,
        curse_effect_value=1,
        upgrade_description=None,
    ),
    "Normality": CardDef(
        id="Normality",
        rarity=CardRarity.CURSE,
        card_type=CardType.CURSE,
        is_unplayable=True,
        is_exhaust=False,
        curse_effect_type=CurseEffectType.LIMIT_CARDS_PER_TURN,
        curse_effect_value=3,
        upgrade_description=None,
    ),
    "Parasite": CardDef(
        id="Parasite",
        rarity=CardRarity.CURSE,
        card_type=CardType.CURSE,
        is_unplayable=True,
        is_exhaust=False,
        curse_effect_type=CurseEffectType.IF_REMOVED_LOSE_MAX_HP,
        curse_effect_value=3,
        upgrade_description=None,
    ),
    "Pride": CardDef(
        id="Pride",
        rarity=CardRarity.CURSE,
        card_type=CardType.CURSE,
        is_unplayable=False,
        cost=1,
        is_exhaust=True,
        is_innate=True,
        curse_effect_type=CurseEffectType.INNATE_COPY_AT_END,
        curse_effect_value=1,
        upgrade_description=None,
    ),
    "Regret": CardDef(
        id="Regret",
        rarity=CardRarity.CURSE,
        card_type=CardType.CURSE,
        is_unplayable=True,
        is_exhaust=False,
        curse_effect_type=CurseEffectType.REGRET_EFFECT,
        curse_effect_value=1,
        upgrade_description=None,
    ),
    "Shame": CardDef(
        id="Shame",
        rarity=CardRarity.CURSE,
        card_type=CardType.CURSE,
        is_unplayable=True,
        is_exhaust=False,
        curse_effect_type=CurseEffectType.END_OF_TURN_FRAIL,
        curse_effect_value=1,
        upgrade_description=None,
    ),
    "Writhe": CardDef(
        id="Writhe",
        rarity=CardRarity.CURSE,
        card_type=CardType.CURSE,
        is_unplayable=True,
        is_exhaust=False,
        curse_effect_type=CurseEffectType.NONE,
        is_innate=True,
        upgrade_description=None,
    ),
}

ALL_CURSE_DEFS = IRONCLAD_CURSE_DEFS


STATUS_CARD_DEFS: dict[str, CardDef] = {
    "Burn": CardDef(
        id="Burn",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.STATUS,
        cost=-2,
        is_unplayable=True,
        curse_effect_type=CurseEffectType.END_OF_TURN_DAMAGE,
        curse_effect_value=2,
        upgrade_description=None,
    ),
    "Burn+": CardDef(
        id="Burn+",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.STATUS,
        cost=-2,
        is_unplayable=True,
        curse_effect_type=CurseEffectType.END_OF_TURN_DAMAGE,
        curse_effect_value=4,
        upgrade_description=None,
    ),
    "Dazed": CardDef(
        id="Dazed",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.STATUS,
        cost=-2,
        is_unplayable=True,
        is_ethereal=True,
        curse_effect_type=CurseEffectType.NONE,
        upgrade_description=None,
    ),
    "Slimed": CardDef(
        id="Slimed",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.STATUS,
        cost=1,
        is_exhaust=True,
        is_unplayable=False,
        upgrade_description=None,
    ),
    "Void": CardDef(
        id="Void",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.STATUS,
        cost=-2,
        is_unplayable=True,
        is_ethereal=True,
        curse_effect_type=CurseEffectType.ON_CARD_PLAYED_LOSE_HP,
        curse_effect_value=1,
        upgrade_description=None,
    ),
    "Wound": CardDef(
        id="Wound",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.STATUS,
        cost=-2,
        is_unplayable=True,
        curse_effect_type=CurseEffectType.NONE,
        upgrade_description=None,
        name_cn="浼ゅ彛",
    ),
}

WATCHER_SPECIAL_DEFS: dict[str, CardDef] = {
    "Beta": CardDef(
        id="Beta",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.SKILL,
        cost=2,
        is_exhaust=True,
        is_unplayable=False,
        upgrade_cost=1,
    ),
    "Miracle": CardDef(
        id="Miracle",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.SKILL,
        cost=0,
        is_exhaust=True,
        is_unplayable=False,
    ),
    "Insight": CardDef(
        id="Insight",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=2,
        is_exhaust=True,
        is_retain=True,
        is_unplayable=False,
        upgrade_magic_number=1,
    ),
    "Expunger": CardDef(
        id="Expunger",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=9,
        base_magic_number=9,
        is_ethereal=True,
        is_unplayable=False,
    ),
    "Omega": CardDef(
        id="Omega",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.POWER,
        cost=3,
        base_magic_number=50,
        is_unplayable=False,
        upgrade_magic_number=10,
    ),
    "Safety": CardDef(
        id="Safety",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.SKILL,
        cost=1,
        base_block=12,
        is_exhaust=True,
        is_retain=True,
        upgrade_block=4,
    ),
    "Smite": CardDef(
        id="Smite",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=12,
        is_exhaust=True,
        is_retain=True,
    ),
    "ThroughViolence": CardDef(
        id="ThroughViolence",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.ATTACK,
        cost=0,
        base_damage=20,
        is_exhaust=True,
        is_retain=True,
    ),
}

COLORLESS_ALL_DEFS: dict[str, CardDef] = {
    "Apotheosis": CardDef(
        id="Apotheosis",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=2,
        is_exhaust=True,
        upgrade_cost=1,
    ),
    "Madness": CardDef(
        id="Madness",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=1,
        is_exhaust=True,
        upgrade_cost=0,
    ),
    "BandageUp": CardDef(
        id="BandageUp",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=4,
        is_exhaust=True,
        upgrade_magic_number=2,
        name_cn="包扎",
    ),
    "DramaticEntrance": CardDef(
        id="DramaticEntrance",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=0,
        base_damage=8,
        is_exhaust=True,
        is_innate=True,
        upgrade_damage=4,
        name_cn="闪亮登场",
    ),
    "Enlightenment": CardDef(
        id="Enlightenment",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        name_cn="开悟",
    ),
    "Discovery": CardDef(
        id="Discovery",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=1,
        is_exhaust=True,
        upgrade_exhaust=False,
        name_cn="发现",
    ),
    "Forethought": CardDef(
        id="Forethought",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        name_cn="预谋",
    ),
    "Impatience": CardDef(
        id="Impatience",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=2,
        upgrade_magic_number=1,
        name_cn="不耐烦",
    ),
    "JAX": CardDef(
        id="JAX",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=2,
        upgrade_magic_number=1,
        name_cn="J.A.X.强化",
    ),
    "JackOfAllTrades": CardDef(
        id="JackOfAllTrades",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=1,
        is_exhaust=True,
        upgrade_magic_number=1,
        name_cn="花样百出",
    ),
    "Magnetism": CardDef(
        id="Magnetism",
        rarity=CardRarity.RARE,
        card_type=CardType.POWER,
        cost=2,
        base_magic_number=1,
        upgrade_cost=1,
        name_cn="\u78c1\u529b",
    ),
    "MasterOfStrategy": CardDef(
        id="MasterOfStrategy",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=3,
        is_exhaust=True,
        upgrade_magic_number=1,
    ),
    "Mayhem": CardDef(
        id="Mayhem",
        rarity=CardRarity.RARE,
        card_type=CardType.POWER,
        cost=2,
        base_magic_number=1,
        upgrade_cost=1,
        name_cn="\u6df7\u6c8c",
    ),
    "MindBlast": CardDef(
        id="MindBlast",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=2,
        is_innate=True,
        upgrade_cost=1,
        name_cn="心灵震慑",
    ),
    "Panache": CardDef(
        id="Panache",
        rarity=CardRarity.RARE,
        card_type=CardType.POWER,
        cost=0,
        base_magic_number=10,
        upgrade_magic_number=4,
        name_cn="\u8f89\u8000",
    ),
    "Purity": CardDef(
        id="Purity",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=3,
        is_exhaust=True,
        upgrade_magic_number=2,
        name_cn="净化",
    ),
    "RitualDagger": CardDef(
        id="RitualDagger",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=15,
        base_magic_number=3,
        is_exhaust=True,
        upgrade_magic_number=2,
        name_cn="\u4eea\u5f0f\u5315\u9996",
    ),
    "SadisticNature": CardDef(
        id="SadisticNature",
        rarity=CardRarity.RARE,
        card_type=CardType.POWER,
        cost=0,
        base_magic_number=5,
        upgrade_magic_number=2,
        name_cn="\u65bd\u8650\u6210\u6027",
    ),
    "Blind": CardDef(
        id="Blind",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=2,
    ),
    "DeepBreath": CardDef(
        id="DeepBreath",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=1,
        upgrade_magic_number=1,
    ),
    "Finesse": CardDef(
        id="Finesse",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_block=2,
        upgrade_block=2,
    ),
    "FlashOfSteel": CardDef(
        id="FlashOfSteel",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=0,
        base_damage=3,
    ),
    "GoodInstincts": CardDef(
        id="GoodInstincts",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_block=6,
        upgrade_block=3,
    ),
    "HandOfGreed": CardDef(
        id="HandOfGreed",
        rarity=CardRarity.RARE,
        card_type=CardType.ATTACK,
        cost=2,
        base_damage=20,
        base_magic_number=20,
        upgrade_damage=5,
        upgrade_magic_number=5,
    ),
    "Panacea": CardDef(
        id="Panacea",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=1,
        is_exhaust=True,
        upgrade_magic_number=1,
    ),
    "Trip": CardDef(
        id="Trip",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=2,
    ),
    "DarkShackles": CardDef(
        id="DarkShackles",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=9,
        is_exhaust=True,
        upgrade_magic_number=6,
    ),
    "SwiftStrike": CardDef(
        id="SwiftStrike",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=0,
        base_damage=7,
    ),
    "PanicButton": CardDef(
        id="PanicButton",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_block=30,
        base_magic_number=2,
        is_exhaust=True,
        upgrade_block=10,
    ),
    "Chrysalis": CardDef(
        id="Chrysalis",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=2,
        base_magic_number=3,
        is_exhaust=True,
        upgrade_magic_number=2,
        name_cn="结茧",
    ),
    "Metamorphosis": CardDef(
        id="Metamorphosis",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=2,
        base_magic_number=3,
        is_exhaust=True,
        upgrade_magic_number=2,
        name_cn="羽化",
    ),
    "Violence": CardDef(
        id="Violence",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=3,
        is_exhaust=True,
        upgrade_magic_number=1,
        name_cn="暴力",
    ),
    "SecretTechnique": CardDef(
        id="SecretTechnique",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=0,
        is_exhaust=True,
        upgrade_exhaust=False,
        name_cn="秘密技法",
    ),
    "SecretWeapon": CardDef(
        id="SecretWeapon",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=0,
        is_exhaust=True,
        upgrade_exhaust=False,
        name_cn="秘密武器",
    ),
    "ThinkingAhead": CardDef(
        id="ThinkingAhead",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=0,
        is_exhaust=True,
        upgrade_exhaust=False,
        name_cn="深谋远虑",
    ),
    "TheBomb": CardDef(
        id="TheBomb",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=2,
        base_magic_number=40,
        name_cn="\u70b8\u5f39",
    ),
    "Transmutation": CardDef(
        id="Transmutation",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=-1,
        is_exhaust=True,
        name_cn="\u5b33\u53d8",
    ),
    "Bite": CardDef(
        id="Bite",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=7,
        base_magic_number=2,
        upgrade_magic_number=1,
    ),
    "Apparition": CardDef(
        id="Apparition",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.SKILL,
        cost=1,
        base_magic_number=1,
        is_exhaust=True,
        is_ethereal=True,
    ),
}

SILENT_SPECIAL_DEFS: dict[str, CardDef] = {
    "Shiv": CardDef(
        id="Shiv",
        rarity=CardRarity.SPECIAL,
        card_type=CardType.ATTACK,
        cost=0,
        base_damage=4,
        is_exhaust=True,
        is_unplayable=False,
        name_cn="Shiv",
    ),
}

SILENT_ALL_DEFS: dict[str, CardDef] = {
    "Neutralize": CardDef(
        id="Neutralize",
        rarity=CardRarity.BASIC,
        card_type=CardType.ATTACK,
        cost=0,
        base_damage=3,
        base_magic_number=1,
        upgrade_damage=1,
        upgrade_magic_number=1,
        name_cn="涓拰",
    ),
    "Survivor": CardDef(
        id="Survivor",
        rarity=CardRarity.BASIC,
        card_type=CardType.SKILL,
        cost=1,
        base_block=8,
        base_magic_number=1,
        upgrade_block=3,
        name_cn="Survivor",
    ),
    "Slice": CardDef(
        id="Slice",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=0,
        base_damage=6,
        upgrade_damage=3,
        name_cn="鍒囧壊",
    ),
    "QuickSlash": CardDef(
        id="QuickSlash",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=8,
        base_magic_number=1,
        upgrade_damage=4,
        name_cn="杩呮嵎鏂╁嚮",
    ),
    "SuckerPunch": CardDef(
        id="SuckerPunch",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=7,
        base_magic_number=1,
        upgrade_damage=2,
        upgrade_magic_number=1,
        name_cn="绐佽",
    ),
    "Backflip": CardDef(
        id="Backflip",
        rarity=CardRarity.COMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_block=5,
        base_magic_number=2,
        upgrade_block=3,
        name_cn="Backflip",
    ),
    "Dash": CardDef(
        id="Dash",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=2,
        base_damage=10,
        base_block=10,
        upgrade_damage=3,
        upgrade_block=3,
        name_cn="鐚涘啿",
    ),
    "PiercingWail": CardDef(
        id="PiercingWail",
        rarity=CardRarity.COMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_magic_number=6,
        is_exhaust=True,
        upgrade_magic_number=2,
        name_cn="PiercingWail",
    ),
    "DeadlyPoison": CardDef(
        id="DeadlyPoison",
        rarity=CardRarity.COMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_magic_number=5,
        upgrade_magic_number=2,
        name_cn="閼锋潙鎳″В鎺曞祩",
    ),
    "PoisonedStab": CardDef(
        id="PoisonedStab",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=6,
        base_magic_number=3,
        upgrade_damage=2,
        upgrade_magic_number=1,
        name_cn="濞ｎ剚鐦ㄩ崠鏇㈩浕",
    ),
    "BouncingFlask": CardDef(
        id="BouncingFlask",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=2,
        base_magic_number=3,
        upgrade_magic_number=1,
        name_cn="瀵瀵氶懡顖滄懕",
    ),
    "NoxiousFumes": CardDef(
        id="NoxiousFumes",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.POWER,
        cost=1,
        base_magic_number=2,
        upgrade_magic_number=1,
        name_cn="NoxiousFumes",
    ),
    "Footwork": CardDef(
        id="Footwork",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.POWER,
        cost=1,
        base_magic_number=2,
        upgrade_magic_number=1,
        name_cn="Footwork",
    ),
    "LegSweep": CardDef(
        id="LegSweep",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=2,
        base_block=11,
        base_magic_number=2,
        upgrade_block=3,
        name_cn="LegSweep",
    ),
    "Terror": CardDef(
        id="Terror",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_magic_number=99,
        is_exhaust=True,
        upgrade_cost=0,
        name_cn="Terror",
    ),
    "Malaise": CardDef(
        id="Malaise",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=-1,
        base_magic_number=0,
        is_exhaust=True,
        upgrade_magic_number=1,
        name_cn="Malaise",
    ),
    "Catalyst": CardDef(
        id="Catalyst",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=1,
        is_exhaust=True,
        name_cn="Catalyst",
    ),
    "CripplingCloud": CardDef(
        id="CripplingCloud",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=2,
        base_magic_number=4,
        is_exhaust=True,
        upgrade_magic_number=3,
        name_cn="閸撱儳姊炬稊瀣╃隘",
    ),
    "CorpseExplosion": CardDef(
        id="CorpseExplosion",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=2,
        base_magic_number=6,
        upgrade_magic_number=3,
        name_cn="鐏忕褰夐悥鍡欏仮",
    ),
    "CloakAndDagger": CardDef(
        id="CloakAndDagger",
        rarity=CardRarity.COMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_block=6,
        base_magic_number=1,
        upgrade_block=2,
        upgrade_magic_number=1,
        name_cn="CloakAndDagger",
    ),
    "BladeDance": CardDef(
        id="BladeDance",
        rarity=CardRarity.COMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_magic_number=3,
        upgrade_magic_number=1,
        name_cn="BladeDance",
    ),
    "Prepared": CardDef(
        id="Prepared",
        rarity=CardRarity.COMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=1,
        upgrade_magic_number=1,
        name_cn="Prepared",
    ),
    "Acrobatics": CardDef(
        id="Acrobatics",
        rarity=CardRarity.COMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_magic_number=3,
        upgrade_magic_number=1,
        name_cn="Acrobatics",
    ),
    "Bane": CardDef(
        id="Bane",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=7,
        upgrade_damage=3,
        name_cn="Bane",
    ),
    "DaggerSpray": CardDef(
        id="DaggerSpray",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=4,
        upgrade_damage=2,
        name_cn="DaggerSpray",
    ),
    "DaggerThrow": CardDef(
        id="DaggerThrow",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=9,
        upgrade_damage=3,
        name_cn="DaggerThrow",
    ),
    "Deflect": CardDef(
        id="Deflect",
        rarity=CardRarity.COMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_block=4,
        upgrade_block=3,
        name_cn="Deflect",
    ),
    "DodgeAndRoll": CardDef(
        id="DodgeAndRoll",
        rarity=CardRarity.COMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_block=4,
        upgrade_block=2,
        name_cn="DodgeAndRoll",
    ),
    "FlyingKnee": CardDef(
        id="FlyingKnee",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=8,
        upgrade_damage=3,
        name_cn="FlyingKnee",
    ),
    "SneakyStrike": CardDef(
        id="SneakyStrike",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=2,
        base_damage=12,
        upgrade_damage=4,
        name_cn="SneakyStrike",
    ),
    "Reflex": CardDef(
        id="Reflex",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=-2,
        base_magic_number=2,
        is_unplayable=True,
        upgrade_magic_number=1,
        name_cn="Reflex",
    ),
    "Tactician": CardDef(
        id="Tactician",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=-2,
        base_magic_number=1,
        is_unplayable=True,
        upgrade_magic_number=1,
        name_cn="Tactician",
    ),
    "Eviscerate": CardDef(
        id="Eviscerate",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=3,
        base_damage=7,
        base_magic_number=3,
        upgrade_damage=1,
        name_cn="Eviscerate",
    ),
    "Concentrate": CardDef(
        id="Concentrate",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=3,
        upgrade_magic_number=-1,
        name_cn="Concentrate",
    ),
    "Outmaneuver": CardDef(
        id="Outmaneuver",
        rarity=CardRarity.COMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_magic_number=2,
        upgrade_magic_number=1,
        name_cn="Outmaneuver",
    ),
    "CalculatedGamble": CardDef(
        id="CalculatedGamble",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        is_exhaust=True,
        name_cn="CalculatedGamble",
    ),
    "Accuracy": CardDef(
        id="Accuracy",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.POWER,
        cost=1,
        base_magic_number=4,
        upgrade_magic_number=2,
        name_cn="Accuracy",
    ),
    "Finisher": CardDef(
        id="Finisher",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=6,
        upgrade_damage=2,
        name_cn="Finisher",
    ),
    "Expertise": CardDef(
        id="Expertise",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_magic_number=6,
        upgrade_magic_number=1,
        name_cn="Expertise",
    ),
    "WellLaidPlans": CardDef(
        id="WellLaidPlans",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.POWER,
        cost=1,
        base_magic_number=1,
        upgrade_magic_number=1,
        name_cn="WellLaidPlans",
    ),
    "Backstab": CardDef(
        id="Backstab",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=0,
        base_damage=11,
        is_innate=True,
        is_exhaust=True,
        upgrade_damage=4,
        name_cn="Backstab",
    ),
    "Blur": CardDef(
        id="Blur",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_block=5,
        upgrade_block=3,
        name_cn="Blur",
    ),
    "Caltrops": CardDef(
        id="Caltrops",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.POWER,
        cost=1,
        base_magic_number=3,
        upgrade_magic_number=2,
        name_cn="Caltrops",
    ),
    "Choke": CardDef(
        id="Choke",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=2,
        base_damage=12,
        base_magic_number=3,
        upgrade_magic_number=2,
        name_cn="Choke",
    ),
    "EndlessAgony": CardDef(
        id="EndlessAgony",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=0,
        base_damage=4,
        is_exhaust=True,
        upgrade_damage=2,
        name_cn="EndlessAgony",
    ),
    "Flechettes": CardDef(
        id="Flechettes",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=4,
        upgrade_damage=2,
        name_cn="Flechettes",
    ),
    "AllOutAttack": CardDef(
        id="AllOutAttack",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=10,
        upgrade_damage=4,
        name_cn="AllOutAttack",
    ),
    "Distraction": CardDef(
        id="Distraction",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=1,
        is_exhaust=True,
        upgrade_cost=0,
        name_cn="Distraction",
    ),
    "EscapePlan": CardDef(
        id="EscapePlan",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_block=3,
        upgrade_block=2,
        name_cn="EscapePlan",
    ),
    "GlassKnife": CardDef(
        id="GlassKnife",
        rarity=CardRarity.RARE,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=8,
        upgrade_damage=4,
        name_cn="GlassKnife",
    ),
    "HeelHook": CardDef(
        id="HeelHook",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=5,
        upgrade_damage=3,
        name_cn="HeelHook",
    ),
    "MasterfulStab": CardDef(
        id="MasterfulStab",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=0,
        base_damage=12,
        upgrade_damage=4,
        name_cn="MasterfulStab",
    ),
    "Predator": CardDef(
        id="Predator",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=2,
        base_damage=15,
        base_magic_number=2,
        upgrade_damage=5,
        name_cn="Predator",
    ),
    "RiddleWithHoles": CardDef(
        id="RiddleWithHoles",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=2,
        base_damage=3,
        upgrade_damage=1,
        name_cn="RiddleWithHoles",
    ),
    "Skewer": CardDef(
        id="Skewer",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=-1,
        base_damage=7,
        upgrade_damage=3,
        name_cn="Skewer",
    ),
    "InfiniteBlades": CardDef(
        id="InfiniteBlades",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.POWER,
        cost=1,
        base_magic_number=1,
        name_cn="InfiniteBlades",
    ),
    "Burst": CardDef(
        id="Burst",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=1,
        base_magic_number=1,
        upgrade_magic_number=1,
        name_cn="Burst",
    ),
    "ToolsOfTheTrade": CardDef(
        id="ToolsOfTheTrade",
        rarity=CardRarity.RARE,
        card_type=CardType.POWER,
        cost=1,
        base_magic_number=1,
        upgrade_cost=0,
        name_cn="ToolsOfTheTrade",
    ),
    "BulletTime": CardDef(
        id="BulletTime",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=3,
        upgrade_cost=2,
        name_cn="BulletTime",
    ),
    "Setup": CardDef(
        id="Setup",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=1,
        upgrade_cost=0,
        name_cn="Setup",
    ),
    "ThousandCuts": CardDef(
        id="ThousandCuts",
        rarity=CardRarity.RARE,
        card_type=CardType.POWER,
        cost=2,
        base_magic_number=1,
        upgrade_magic_number=1,
        name_cn="ThousandCuts",
    ),
    "AfterImage": CardDef(
        id="AfterImage",
        rarity=CardRarity.RARE,
        card_type=CardType.POWER,
        cost=1,
        base_magic_number=1,
        upgrade_innate=True,
        name_cn="AfterImage",
    ),
    "Alchemize": CardDef(
        id="Alchemize",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=1,
        is_exhaust=True,
        upgrade_cost=0,
        name_cn="Alchemize",
    ),
    "Adrenaline": CardDef(
        id="Adrenaline",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=1,
        is_exhaust=True,
        upgrade_magic_number=1,
        name_cn="鑲句笂鑵虹礌",
    ),
    "Envenom": CardDef(
        id="Envenom",
        rarity=CardRarity.RARE,
        card_type=CardType.POWER,
        cost=2,
        base_magic_number=1,
        upgrade_cost=1,
        name_cn="Envenom",
    ),
    "GrandFinale": CardDef(
        id="GrandFinale",
        rarity=CardRarity.RARE,
        card_type=CardType.ATTACK,
        cost=0,
        base_damage=50,
        upgrade_damage=10,
        name_cn="GrandFinale",
    ),
    "PhantasmalKiller": CardDef(
        id="PhantasmalKiller",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=1,
        upgrade_cost=0,
        name_cn="PhantasmalKiller",
    ),
    "WraithForm": CardDef(
        id="WraithForm",
        rarity=CardRarity.RARE,
        card_type=CardType.POWER,
        cost=3,
        base_magic_number=2,
        upgrade_magic_number=1,
        name_cn="WraithForm",
    ),
    "StormOfSteel": CardDef(
        id="StormOfSteel",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=1,
        name_cn="StormOfSteel",
    ),
    "Nightmare": CardDef(
        id="Nightmare",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=3,
        base_magic_number=3,
        is_exhaust=True,
        upgrade_cost=2,
        name_cn="Nightmare",
    ),
    "Doppelganger": CardDef(
        id="Doppelganger",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=-1,
        is_exhaust=True,
        name_cn="Doppelganger",
    ),
    "Unload": CardDef(
        id="Unload",
        rarity=CardRarity.RARE,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=14,
        upgrade_damage=4,
        name_cn="Unload",
    ),
    "DieDieDie": CardDef(
        id="DieDieDie",
        rarity=CardRarity.RARE,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=13,
        is_exhaust=True,
        upgrade_damage=4,
        name_cn="DieDieDie",
    ),
}


DEFECT_ALL_DEFS: dict[str, CardDef] = {
    "Strike_B": CardDef(
        id="Strike_B",
        rarity=CardRarity.BASIC,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=6,
        upgrade_damage=3,
        name_cn="Strike_B",
    ),
    "Defend_B": CardDef(
        id="Defend_B",
        rarity=CardRarity.BASIC,
        card_type=CardType.SKILL,
        cost=1,
        base_block=5,
        upgrade_block=3,
        name_cn="Defend_B",
    ),
    "Zap": CardDef(
        id="Zap",
        rarity=CardRarity.BASIC,
        card_type=CardType.SKILL,
        cost=1,
        base_magic_number=1,
        upgrade_cost=0,
        name_cn="Zap",
    ),
    "Dualcast": CardDef(
        id="Dualcast",
        rarity=CardRarity.BASIC,
        card_type=CardType.SKILL,
        cost=1,
        upgrade_cost=0,
        name_cn="Dualcast",
    ),
    "BallLightning": CardDef(
        id="BallLightning",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=7,
        base_magic_number=1,
        upgrade_damage=3,
        name_cn="BallLightning",
    ),
    "ColdSnap": CardDef(
        id="ColdSnap",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=6,
        base_magic_number=1,
        upgrade_damage=3,
        name_cn="ColdSnap",
    ),
    "Coolheaded": CardDef(
        id="Coolheaded",
        rarity=CardRarity.COMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_magic_number=1,
        upgrade_magic_number=1,
        name_cn="Coolheaded",
    ),
    "CompileDriver": CardDef(
        id="CompileDriver",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=7,
        base_magic_number=1,
        upgrade_damage=3,
        name_cn="CompileDriver",
    ),
    "GoForTheEyes": CardDef(
        id="GoForTheEyes",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=0,
        base_damage=3,
        base_magic_number=1,
        upgrade_damage=1,
        upgrade_magic_number=1,
        name_cn="GoForTheEyes",
    ),
    "BeamCell": CardDef(
        id="BeamCell",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=0,
        base_damage=3,
        base_magic_number=1,
        upgrade_damage=1,
        upgrade_magic_number=1,
        name_cn="BeamCell",
    ),
    "Recursion": CardDef(
        id="Recursion",
        rarity=CardRarity.COMMON,
        card_type=CardType.SKILL,
        cost=1,
        upgrade_cost=0,
        name_cn="Recursion",
    ),
    "Turbo": CardDef(
        id="Turbo",
        rarity=CardRarity.COMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=2,
        upgrade_magic_number=1,
        name_cn="Turbo",
    ),
    "ConserveBattery": CardDef(
        id="ConserveBattery",
        rarity=CardRarity.COMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_block=7,
        upgrade_block=3,
        name_cn="ConserveBattery",
    ),
    "Claw": CardDef(
        id="Claw",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=0,
        base_damage=3,
        base_magic_number=2,
        upgrade_damage=2,
        name_cn="Claw",
    ),
    "Tempest": CardDef(
        id="Tempest",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=-1,
        is_exhaust=True,
        name_cn="Tempest",
    ),
    "SweepingBeam": CardDef(
        id="SweepingBeam",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=6,
        base_magic_number=1,
        upgrade_damage=3,
        name_cn="SweepingBeam",
    ),
    "Barrage": CardDef(
        id="Barrage",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=4,
        upgrade_damage=2,
        name_cn="Barrage",
    ),
    "Hologram": CardDef(
        id="Hologram",
        rarity=CardRarity.COMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_block=3,
        is_exhaust=True,
        upgrade_block=2,
        upgrade_exhaust=False,
        name_cn="Hologram",
    ),
    "Rebound": CardDef(
        id="Rebound",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=9,
        upgrade_damage=3,
        name_cn="Rebound",
    ),
    "Streamline": CardDef(
        id="Streamline",
        rarity=CardRarity.COMMON,
        card_type=CardType.ATTACK,
        cost=2,
        base_damage=15,
        base_magic_number=1,
        upgrade_damage=5,
        name_cn="Streamline",
    ),
    "Leap": CardDef(
        id="Leap",
        rarity=CardRarity.COMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_block=9,
        upgrade_block=3,
        name_cn="Leap",
    ),
    "Defragment": CardDef(
        id="Defragment",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.POWER,
        cost=1,
        base_magic_number=1,
        upgrade_magic_number=1,
        name_cn="Defragment",
    ),
    "Blizzard": CardDef(
        id="Blizzard",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=0,
        base_magic_number=2,
        upgrade_magic_number=1,
        name_cn="Blizzard",
    ),
    "Lockon": CardDef(
        id="Lockon",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=8,
        base_magic_number=2,
        upgrade_damage=3,
        upgrade_magic_number=1,
        name_cn="Lockon",
    ),
    "Bullseye": CardDef(
        id="Bullseye",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=8,
        base_magic_number=2,
        upgrade_damage=3,
        upgrade_magic_number=1,
        name_cn="Bullseye",
    ),
    "Darkness": CardDef(
        id="Darkness",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_magic_number=1,
        name_cn="Darkness",
    ),
    "Chill": CardDef(
        id="Chill",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        is_exhaust=True,
        upgrade_innate=True,
        name_cn="Chill",
    ),
    "DoomAndGloom": CardDef(
        id="DoomAndGloom",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=2,
        base_damage=10,
        base_magic_number=1,
        upgrade_damage=4,
        name_cn="DoomAndGloom",
    ),
    "Loop": CardDef(
        id="Loop",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.POWER,
        cost=1,
        base_magic_number=1,
        upgrade_magic_number=1,
        name_cn="Loop",
    ),
    "Consume": CardDef(
        id="Consume",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=2,
        base_magic_number=2,
        upgrade_magic_number=1,
        name_cn="Consume",
    ),
    "DoubleEnergy": CardDef(
        id="DoubleEnergy",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=1,
        is_exhaust=True,
        upgrade_cost=0,
        name_cn="DoubleEnergy",
    ),
    "Recycle": CardDef(
        id="Recycle",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=1,
        upgrade_cost=0,
        name_cn="Recycle",
    ),
    "Fusion": CardDef(
        id="Fusion",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=2,
        base_magic_number=1,
        upgrade_cost=1,
        name_cn="Fusion",
    ),
    "Capacitor": CardDef(
        id="Capacitor",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.POWER,
        cost=1,
        base_magic_number=2,
        upgrade_magic_number=1,
        name_cn="Capacitor",
    ),
    "Equilibrium": CardDef(
        id="Equilibrium",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=2,
        base_block=13,
        base_magic_number=1,
        upgrade_block=3,
        name_cn="Equilibrium",
    ),
    "ForceField": CardDef(
        id="ForceField",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=4,
        base_block=12,
        upgrade_block=4,
        name_cn="ForceField",
    ),
    "Storm": CardDef(
        id="Storm",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.POWER,
        cost=1,
        base_magic_number=1,
        upgrade_innate=True,
        name_cn="Storm",
    ),
    "StaticDischarge": CardDef(
        id="StaticDischarge",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.POWER,
        cost=1,
        base_magic_number=1,
        upgrade_magic_number=1,
        name_cn="StaticDischarge",
    ),
    "Heatsinks": CardDef(
        id="Heatsinks",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.POWER,
        cost=1,
        base_magic_number=1,
        upgrade_magic_number=1,
        name_cn="Heatsinks",
    ),
    "FTL": CardDef(
        id="FTL",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=0,
        base_damage=5,
        base_magic_number=3,
        upgrade_damage=1,
        upgrade_magic_number=1,
        name_cn="FTL",
    ),
    "Glacier": CardDef(
        id="Glacier",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=2,
        base_block=7,
        base_magic_number=2,
        upgrade_block=3,
        name_cn="Glacier",
    ),
    "GeneticAlgorithm": CardDef(
        id="GeneticAlgorithm",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_block=1,
        base_magic_number=2,
        is_exhaust=True,
        upgrade_magic_number=1,
        name_cn="GeneticAlgorithm",
    ),
    "HelloWorld": CardDef(
        id="HelloWorld",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.POWER,
        cost=1,
        base_magic_number=1,
        upgrade_innate=True,
        name_cn="HelloWorld",
    ),
    "Stack": CardDef(
        id="Stack",
        rarity=CardRarity.COMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_block=0,
        upgrade_block=3,
        name_cn="Stack",
    ),
    "Melter": CardDef(
        id="Melter",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=10,
        upgrade_damage=4,
        name_cn="Melter",
    ),
    "RipAndTear": CardDef(
        id="RipAndTear",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=7,
        base_magic_number=2,
        upgrade_damage=2,
        name_cn="RipAndTear",
    ),
    "Reprogram": CardDef(
        id="Reprogram",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_magic_number=1,
        upgrade_magic_number=1,
        name_cn="Reprogram",
    ),
    "ReinforcedBody": CardDef(
        id="ReinforcedBody",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=-1,
        base_block=7,
        upgrade_block=2,
        name_cn="ReinforcedBody",
    ),
    "Sunder": CardDef(
        id="Sunder",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=3,
        base_damage=24,
        upgrade_damage=8,
        name_cn="Sunder",
    ),
    "Skim": CardDef(
        id="Skim",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_magic_number=3,
        upgrade_magic_number=1,
        name_cn="Skim",
    ),
    "Aggregate": CardDef(
        id="Aggregate",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_magic_number=4,
        upgrade_magic_number=-1,
        name_cn="Aggregate",
    ),
    "AutoShields": CardDef(
        id="AutoShields",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_block=11,
        upgrade_block=4,
        name_cn="AutoShields",
    ),
    "BootSequence": CardDef(
        id="BootSequence",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_block=10,
        is_exhaust=True,
        is_innate=True,
        upgrade_block=3,
        name_cn="BootSequence",
    ),
    "SelfRepair": CardDef(
        id="SelfRepair",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.POWER,
        cost=1,
        base_magic_number=7,
        upgrade_magic_number=3,
        name_cn="SelfRepair",
    ),
    "Scrape": CardDef(
        id="Scrape",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=7,
        base_magic_number=4,
        upgrade_damage=3,
        upgrade_magic_number=1,
        name_cn="Scrape",
    ),
    "SteamBarrier": CardDef(
        id="SteamBarrier",
        rarity=CardRarity.COMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_block=6,
        upgrade_block=2,
        name_cn="SteamBarrier",
    ),
    "WhiteNoise": CardDef(
        id="WhiteNoise",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=1,
        is_exhaust=True,
        upgrade_cost=0,
        name_cn="WhiteNoise",
    ),
    "Chaos": CardDef(
        id="Chaos",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=1,
        base_magic_number=1,
        upgrade_magic_number=1,
        name_cn="Chaos",
    ),
    "Overclock": CardDef(
        id="Overclock",
        rarity=CardRarity.UNCOMMON,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=2,
        upgrade_magic_number=1,
        name_cn="Overclock",
    ),
    "CoreSurge": CardDef(
        id="CoreSurge",
        rarity=CardRarity.RARE,
        card_type=CardType.ATTACK,
        cost=1,
        base_damage=11,
        base_magic_number=1,
        is_exhaust=True,
        upgrade_damage=4,
        name_cn="CoreSurge",
    ),
    "Buffer": CardDef(
        id="Buffer",
        rarity=CardRarity.RARE,
        card_type=CardType.POWER,
        cost=2,
        base_magic_number=1,
        upgrade_magic_number=1,
        name_cn="Buffer",
    ),
    "MachineLearning": CardDef(
        id="MachineLearning",
        rarity=CardRarity.RARE,
        card_type=CardType.POWER,
        cost=1,
        base_magic_number=1,
        upgrade_innate=True,
        name_cn="MachineLearning",
    ),
    "Reboot": CardDef(
        id="Reboot",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=4,
        is_exhaust=True,
        upgrade_magic_number=2,
        name_cn="Reboot",
    ),
    "Seek": CardDef(
        id="Seek",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=1,
        is_exhaust=True,
        upgrade_magic_number=1,
        name_cn="Seek",
    ),
    "CreativeAI": CardDef(
        id="CreativeAI",
        rarity=CardRarity.RARE,
        card_type=CardType.POWER,
        cost=3,
        base_magic_number=1,
        upgrade_cost=2,
        name_cn="CreativeAI",
    ),
    "Fission": CardDef(
        id="Fission",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=0,
        base_magic_number=1,
        is_exhaust=True,
        name_cn="Fission",
    ),
    "MultiCast": CardDef(
        id="MultiCast",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=-1,
        name_cn="MultiCast",
    ),
    "Rainbow": CardDef(
        id="Rainbow",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=2,
        is_exhaust=True,
        upgrade_exhaust=False,
        name_cn="Rainbow",
    ),
    "MeteorStrike": CardDef(
        id="MeteorStrike",
        rarity=CardRarity.RARE,
        card_type=CardType.ATTACK,
        cost=5,
        base_damage=24,
        base_magic_number=3,
        upgrade_damage=6,
        name_cn="MeteorStrike",
    ),
    "Electrodynamics": CardDef(
        id="Electrodynamics",
        rarity=CardRarity.RARE,
        card_type=CardType.POWER,
        cost=2,
        base_magic_number=2,
        upgrade_magic_number=1,
        name_cn="Electrodynamics",
    ),
    "BiasedCognition": CardDef(
        id="BiasedCognition",
        rarity=CardRarity.RARE,
        card_type=CardType.POWER,
        cost=1,
        base_magic_number=4,
        upgrade_magic_number=1,
        name_cn="BiasedCognition",
    ),
    "Hyperbeam": CardDef(
        id="Hyperbeam",
        rarity=CardRarity.RARE,
        card_type=CardType.ATTACK,
        cost=2,
        base_damage=26,
        base_magic_number=3,
        upgrade_damage=8,
        name_cn="Hyperbeam",
    ),
    "AllForOne": CardDef(
        id="AllForOne",
        rarity=CardRarity.RARE,
        card_type=CardType.ATTACK,
        cost=2,
        base_damage=10,
        upgrade_damage=4,
        name_cn="AllForOne",
    ),
    "Amplify": CardDef(
        id="Amplify",
        rarity=CardRarity.RARE,
        card_type=CardType.SKILL,
        cost=1,
        base_magic_number=1,
        upgrade_magic_number=1,
        is_exhaust=False,
        name_cn="Amplify",
    ),
    "EchoForm": CardDef(
        id="EchoForm",
        rarity=CardRarity.RARE,
        card_type=CardType.POWER,
        cost=3,
        is_ethereal=True,
        upgrade_ethereal=False,
        name_cn="EchoForm",
    ),
}

_CARD_DEF_GROUPS: tuple[dict[str, CardDef], ...] = (
    IRONCLAD_ALL_DEFS,
    WATCHER_ALL_DEFS,
    SILENT_ALL_DEFS,
    DEFECT_ALL_DEFS,
    ALL_CURSE_DEFS,
    STATUS_CARD_DEFS,
    WATCHER_SPECIAL_DEFS,
    COLORLESS_ALL_DEFS,
    SILENT_SPECIAL_DEFS,
)


def _apply_card_def_overrides(overrides: dict[str, dict[str, object]]) -> None:
    for card_id, changes in overrides.items():
        for defs in _CARD_DEF_GROUPS:
            if card_id in defs:
                defs[card_id] = replace(defs[card_id], **changes)
                break
        else:
            raise KeyError(f"unknown card def override target: {card_id}")


_IRONCLAD_COSTS = {
    "Strike": 1,
    "Defend": 1,
    "Bash": 2,
    "Anger": 0,
    "Armaments": 1,
    "BodySlam": 1,
    "Clash": 0,
    "Cleave": 1,
    "Clothesline": 2,
    "Flex": 0,
    "Havoc": 1,
    "Headbutt": 1,
    "HeavyBlade": 2,
    "IronWave": 1,
    "PerfectedStrike": 2,
    "PommelStrike": 1,
    "ShrugItOff": 1,
    "SwordBoomerang": 1,
    "Thunderclap": 1,
    "TrueGrit": 1,
    "TwinStrike": 1,
    "Warcry": 0,
    "WildStrike": 1,
    "BattleTrance": 0,
    "BloodforBlood": 4,
    "Bloodletting": 0,
    "BurningPact": 1,
    "Carnage": 2,
    "Combust": 1,
    "DarkEmbrace": 2,
    "Disarm": 1,
    "Dropkick": 1,
    "DualWield": 1,
    "Entrench": 2,
    "Evolve": 1,
    "FeelNoPain": 1,
    "FireBreathing": 1,
    "FlameBarrier": 2,
    "GhostlyArmor": 1,
    "Hemokinesis": 1,
    "InfernalBlade": 1,
    "Inflame": 1,
    "Intimidate": 0,
    "Metallicize": 1,
    "PowerThrough": 1,
    "Pummel": 1,
    "Rage": 0,
    "Rampage": 1,
    "RecklessCharge": 0,
    "Rupture": 1,
    "SearingBlow": 2,
    "SecondWind": 1,
    "SeeingRed": 1,
    "Sentinel": 1,
    "SeverSoul": 2,
    "Shockwave": 2,
    "SpotWeakness": 1,
    "Barricade": 3,
    "Berserk": 0,
    "Bludgeon": 3,
    "Brutality": 0,
    "Corruption": 3,
    "DemonForm": 3,
    "DoubleTap": 1,
    "Exhume": 1,
    "Feed": 1,
    "FiendFire": 2,
    "Immolate": 2,
    "Impervious": 2,
    "Juggernaut": 2,
    "LimitBreak": 1,
    "Offering": 0,
    "Reaper": 2,
    "Uppercut": 2,
    "Whirlwind": -1,
}

_IRONCLAD_BASE_DAMAGE = {
    "Strike": 6,
    "Bash": 8,
    "Anger": 6,
    "BodySlam": 0,
    "Clash": 14,
    "Cleave": 8,
    "Clothesline": 12,
    "Headbutt": 9,
    "HeavyBlade": 14,
    "IronWave": 5,
    "PerfectedStrike": 6,
    "PommelStrike": 9,
    "SwordBoomerang": 3,
    "Thunderclap": 4,
    "TwinStrike": 5,
    "WildStrike": 12,
    "BloodforBlood": 18,
    "Carnage": 20,
    "Dropkick": 5,
    "Hemokinesis": 15,
    "Pummel": 2,
    "Rampage": 8,
    "RecklessCharge": 7,
    "SearingBlow": 12,
    "SeverSoul": 16,
    "Bludgeon": 32,
    "Feed": 10,
    "FiendFire": 7,
    "Immolate": 21,
    "Reaper": 4,
    "Uppercut": 13,
    "Whirlwind": 5,
}

_IRONCLAD_BASE_BLOCK = {
    "Defend": 5,
    "Armaments": 5,
    "IronWave": 5,
    "ShrugItOff": 8,
    "TrueGrit": 7,
    "FlameBarrier": 12,
    "GhostlyArmor": 10,
    "Impervious": 30,
    "Sentinel": 5,
    "Rage": 0,
    "PowerThrough": 15,
}

_IRONCLAD_BASE_MAGIC = {
    "Bash": 2,
    "Armaments": 0,
    "Clothesline": 2,
    "Flex": 2,
    "HeavyBlade": 3,
    "Inflame": 2,
    "PommelStrike": 1,
    "SwordBoomerang": 3,
    "Thunderclap": 0,
    "Warcry": 1,
    "BattleTrance": 3,
    "Bloodletting": 2,
    "Combust": 5,
    "Disarm": 2,
    "Entrench": 0,
    "Evolve": 1,
    "FireBreathing": 6,
    "FlameBarrier": 4,
    "Intimidate": 1,
    "Metallicize": 3,
    "PowerThrough": 0,
    "Pummel": 4,
    "Rage": 3,
    "Rupture": 1,
    "SecondWind": 0,
    "Sentinel": 0,
    "Shockwave": 3,
    "SpotWeakness": 3,
    "Berserk": 2,
    "Brutality": 1,
    "DemonForm": 2,
    "DualWield": 1,
    "DoubleTap": 1,
    "Feed": 3,
    "Offering": 3,
    "Uppercut": 1,
}

_IRONCLAD_UPGRADE_OVERRIDES = {
    "Defend": {"upgrade_block": 3},
    "Strike": {"upgrade_damage": 3},
    "Armaments": {"upgrade_block": 3},
    "Bash": {"upgrade_damage": 2, "upgrade_magic_number": 1, "target_required": True},
    "Anger": {"upgrade_damage": 2, "target_required": True},
    "BodySlam": {"upgrade_cost": 0},
    "Clash": {"upgrade_damage": 4},
    "Cleave": {"upgrade_damage": 3},
    "Clothesline": {"upgrade_damage": 2, "upgrade_magic_number": 1, "target_required": True},
    "Flex": {"upgrade_magic_number": 2},
    "Havoc": {"upgrade_cost": 0, "target_required": False},
    "Headbutt": {"upgrade_damage": 3, "target_required": True},
    "HeavyBlade": {"upgrade_magic_number": 2, "target_required": True},
    "IronWave": {"upgrade_damage": 2},
    "ShrugItOff": {"upgrade_block": 3},
    "PommelStrike": {"upgrade_damage": 1, "upgrade_magic_number": 1, "target_required": True},
    "SwordBoomerang": {"upgrade_damage": 1},
    "Thunderclap": {"upgrade_damage": 3, "upgrade_magic_number": 1},
    "TrueGrit": {"upgrade_block": 2},
    "TwinStrike": {"upgrade_damage": 2},
    "Warcry": {"upgrade_magic_number": 1},
    "WildStrike": {"upgrade_damage": 5},
    "BattleTrance": {"upgrade_magic_number": 1},
    "BloodforBlood": {"upgrade_damage": 4, "upgrade_cost": 3, "target_required": True},
    "Bloodletting": {"upgrade_magic_number": 1},
    "Combust": {"upgrade_magic_number": 2},
    "Disarm": {"upgrade_magic_number": 1},
    "Carnage": {"upgrade_damage": 8, "target_required": True},
    "DualWield": {"upgrade_magic_number": 1},
    "Dropkick": {"upgrade_damage": 3, "target_required": True},
    "Evolve": {"upgrade_magic_number": 1},
    "FireBreathing": {"upgrade_magic_number": 4},
    "FlameBarrier": {"upgrade_block": 4, "upgrade_magic_number": 2},
    "GhostlyArmor": {"upgrade_block": 3},
    "Hemokinesis": {"upgrade_damage": 5, "target_required": True},
    "Inflame": {"upgrade_magic_number": 1},
    "Intimidate": {"upgrade_magic_number": 1},
    "Metallicize": {"upgrade_magic_number": 1},
    "PowerThrough": {"upgrade_block": 5},
    "Pummel": {"upgrade_magic_number": 1, "target_required": True},
    "Rage": {"upgrade_magic_number": 2},
    "RecklessCharge": {"upgrade_damage": 3},
    "Rupture": {"upgrade_magic_number": 1},
    "SecondWind": {"upgrade_magic_number": 2},
    "SeverSoul": {"upgrade_damage": 6},
    "Sentinel": {"upgrade_block": 3, "upgrade_magic_number": 1},
    "Shockwave": {"upgrade_magic_number": 2},
    "SpotWeakness": {"upgrade_magic_number": 1},
    "Berserk": {"upgrade_magic_number": 1},
    "Bludgeon": {"upgrade_damage": 10, "target_required": True},
    "Brutality": {"upgrade_magic_number": 1, "is_innate": True},
    "DemonForm": {"upgrade_magic_number": 1},
    "DoubleTap": {"upgrade_magic_number": 1},
    "Feed": {"upgrade_damage": 2, "upgrade_magic_number": 1, "is_exhaust": True, "target_required": True},
    "FiendFire": {"upgrade_damage": 3},
    "Immolate": {"upgrade_damage": 7},
    "Impervious": {"upgrade_block": 10},
    "Offering": {"upgrade_magic_number": 1, "is_exhaust": True},
    "Reaper": {"upgrade_damage": 1},
    "SeeingRed": {"upgrade_cost": 0, "is_exhaust": True},
    "Uppercut": {"upgrade_magic_number": 1},
    "LimitBreak": {"is_exhaust": True},
    "Whirlwind": {"upgrade_damage": 3},
}


def _apply_ironclad_static_truth() -> None:
    for card_id, definition in list(IRONCLAD_ALL_DEFS.items()):
        changes: dict[str, object] = {}
        if card_id in _IRONCLAD_COSTS:
            changes["cost"] = _IRONCLAD_COSTS[card_id]
        if card_id in _IRONCLAD_BASE_DAMAGE:
            changes["base_damage"] = _IRONCLAD_BASE_DAMAGE[card_id]
        if card_id in _IRONCLAD_BASE_BLOCK:
            changes["base_block"] = _IRONCLAD_BASE_BLOCK[card_id]
        if card_id in _IRONCLAD_BASE_MAGIC:
            changes["base_magic_number"] = _IRONCLAD_BASE_MAGIC[card_id]
        if changes:
            IRONCLAD_ALL_DEFS[card_id] = replace(definition, **changes)
    _apply_card_def_overrides(_IRONCLAD_UPGRADE_OVERRIDES)


_CARD_STATIC_OVERRIDES = {
    "Adrenaline": {"is_exhaust": True},
    "AfterImage": {},
    "Alpha": {"is_innate": True},
    "Amplify": {},
    "Apparition": {"base_magic_number": 0},
    "Armaments": {"base_magic_number": 0},
    "AscendersBane": {"is_ethereal": True},
    "Backflip": {},
    "BattleHymn": {"is_innate": True},
    "Bloodletting": {"is_exhaust": False},
    "Blasphemy": {"is_retain": True},
    "BowlingBash": {"target_required": True},
    "Brilliance": {"target_required": True},
    "Brutality": {"base_magic_number": 0, "is_innate": True},
    "Burn": {"base_magic_number": 2},
    "Burn+": {"base_magic_number": 4},
    "BurningPact": {"base_magic_number": 2},
    "Carnage": {"is_exhaust": False},
    "Chill": {"base_magic_number": 1, "is_innate": True},
    "Clumsy": {"is_ethereal": True},
    "Corruption": {"base_magic_number": 3, "upgrade_cost": 2},
    "CrushJoints": {"target_required": True},
    "CurseOfTheBell": {},
    "Darkness": {"is_exhaust": False},
    "Dropkick": {"is_exhaust": False},
    "EmptyFist": {"target_required": True},
    "Envenom": {"base_magic_number": 0},
    "Establishment": {"is_innate": True},
    "Eviscerate": {"target_required": True},
    "Expunger": {"base_magic_number": 0, "is_ethereal": False, "target_required": True, "upgrade_damage": 6},
    "FearNoEvil": {"target_required": True},
    "FeelNoPain": {"base_magic_number": 3},
    "FlurryOfBlows": {"target_required": True},
    "FlyingSleeves": {"target_required": True},
    "FollowUp": {"target_required": True},
    "GeneticAlgorithm": {"base_block": 1},
    "HelloWorld": {"base_magic_number": 0, "is_innate": True},
    "Hemokinesis": {"base_magic_number": 2},
    "InfiniteBlades": {"base_magic_number": 0, "is_innate": True},
    "Immolate": {"is_exhaust": False},
    "Intimidate": {"is_exhaust": True},
    "Judgement": {"target_required": True},
    "Juggernaut": {"base_magic_number": 5},
    "LessonLearned": {"target_required": True},
    "MachineLearning": {"is_innate": True},
    "Malaise": {"rarity": CardRarity.RARE, "is_exhaust": True, "target_required": True},
    "Miracle": {"is_retain": True},
    "Offering": {"base_magic_number": 3},
    "Outmaneuver": {},
    "PerfectedStrike": {"base_magic_number": 2},
    "Pummel": {"is_exhaust": True, "target_required": True},
    "PowerThrough": {"base_magic_number": 0},
    "Predator": {},
    "PressurePoints": {"target_required": True},
    "QuickSlash": {"base_magic_number": 0},
    "Rampage": {"base_magic_number": 5, "target_required": True},
    "RitualDagger": {"base_damage": 15},
    "SandsOfTime": {"target_required": True},
    "SashWhip": {"target_required": True},
    "SecondWind": {"base_block": 5, "base_magic_number": 0, "upgrade_block": 2},
    "Sentinel": {"base_magic_number": 0, "is_exhaust": False},
    "SearingBlow": {"target_required": True},
    "SeverSoul": {"is_exhaust": False},
    "Shiv": {"base_damage": 4},
    "Shockwave": {"is_exhaust": True},
    "SignatureMove": {"target_required": True},
    "Storm": {"is_innate": True},
    "Survivor": {"base_magic_number": 0},
    "Swivel": {"base_magic_number": 0},
    "TalkToTheHand": {"target_required": True},
    "Tantrum": {"target_required": True},
    "Terror": {},
    "Thunderclap": {"base_magic_number": 0},
    "ToolsOfTheTrade": {},
    "WheelKick": {"target_required": True},
    "WindmillStrike": {"target_required": True},
    "Worship": {"is_retain": True},
}


def _normalize_unplayable_curse_costs() -> None:
    for card_id, definition in list(ALL_CURSE_DEFS.items()):
        if getattr(definition, "is_unplayable", False) and int(getattr(definition, "cost", -1)) == -1:
            ALL_CURSE_DEFS[card_id] = replace(definition, cost=-2)


_apply_ironclad_static_truth()
_normalize_unplayable_curse_costs()
_apply_card_def_overrides(_CARD_STATIC_OVERRIDES)


CARD_DEFS_BY_CHARACTER: dict[str, dict[str, CardDef]] = {
    "IRONCLAD": IRONCLAD_ALL_DEFS,
    "WATCHER": WATCHER_ALL_DEFS,
    "SILENT": SILENT_ALL_DEFS,
    "DEFECT": DEFECT_ALL_DEFS,
}

ALL_COLOR_CARD_DEFS: dict[str, CardDef] = {}
for _defs in CARD_DEFS_BY_CHARACTER.values():
    ALL_COLOR_CARD_DEFS.update(_defs)

ALL_CARD_DEFS: dict[str, CardDef] = {}
ALL_CARD_DEFS.update(ALL_COLOR_CARD_DEFS)
ALL_CARD_DEFS.update(ALL_CURSE_DEFS)
ALL_CARD_DEFS.update(STATUS_CARD_DEFS)
ALL_CARD_DEFS.update(WATCHER_SPECIAL_DEFS)
ALL_CARD_DEFS.update(COLORLESS_ALL_DEFS)
ALL_CARD_DEFS.update(SILENT_SPECIAL_DEFS)

CARD_ID_ALIASES: dict[str, str] = {
    "Adaptation": "Rushdown",
    "AThousandCuts": "ThousandCuts",
    "All For One": "AllForOne",
    "All Out Attack": "AllOutAttack",
    "Ball Lightning": "BallLightning",
    "Auto Shields": "AutoShields",
    "Bandage Up": "BandageUp",
    "Beam Cell": "BeamCell",
    "Biased Cognition": "BiasedCognition",
    "Compile Driver": "CompileDriver",
    "ClearTheMind": "Tranquility",
    "Conserve Battery": "ConserveBattery",
    "Cold Snap": "ColdSnap",
    "Core Surge": "CoreSurge",
    "CripplingPoison": "CripplingCloud",
    "Doom and Gloom": "DoomAndGloom",
    "Dramatic Entrance": "DramaticEntrance",
    "Endless Agony": "EndlessAgony",
    "Echo Form": "EchoForm",
    "Escape Plan": "EscapePlan",
    "Secret Technique": "SecretTechnique",
    "Secret Weapon": "SecretWeapon",
    "Gash": "Claw",
    "Defend_Watcher": "Defend_P",
    "Defend_Blue": "Defend_B",
    "Fasting2": "Fasting",
    "Force Field": "ForceField",
    "Glass Knife": "GlassKnife",
    "Genetic Algorithm": "GeneticAlgorithm",
    "Go for the Eyes": "GoForTheEyes",
    "Heel Hook": "HeelHook",
    "Hello World": "HelloWorld",
    "Hyper Beam": "Hyperbeam",
    "Impulse": "Darkness",
    "J.A.X.": "JAX",
    "Jack Of All Trades": "JackOfAllTrades",
    "LockOn": "Lockon",
    "Lock On": "Lockon",
    "Masterful Stab": "MasterfulStab",
    "Double Energy": "DoubleEnergy",
    "Machine Learning": "MachineLearning",
    "Meteor Strike": "MeteorStrike",
    "Multi-Cast": "MultiCast",
    "Night Terror": "Nightmare",
    "Undo": "Equilibrium",
    "PathToVictory": "PressurePoints",
    "Redo": "Recursion",
    "Reinforced Body": "ReinforcedBody",
    "Riddle With Holes": "RiddleWithHoles",
    "Rip and Tear": "RipAndTear",
    "Ritual Dagger": "RitualDagger",
    "Creative AI": "CreativeAI",
    "BloodForBlood": "BloodforBlood",
    "Bullet Time": "BulletTime",
    "Dark Shackles": "DarkShackles",
    "Dagger Spray": "DaggerSpray",
    "Deep Breath": "DeepBreath",
    "Defend_Red": "Defend",
    "Dodge and Roll": "DodgeAndRoll",
    "Flash of Steel": "FlashOfSteel",
    "Flying Knee": "FlyingKnee",
    "Ghostly": "Apparition",
    "Good Instincts": "GoodInstincts",
    "Grand Finale": "GrandFinale",
    "Hand of Greed": "HandOfGreed",
    "Phantasmal Killer": "PhantasmalKiller",
    "Master of Strategy": "MasterOfStrategy",
    "Mind Blast": "MindBlast",
    "Panic Button": "PanicButton",
    "Self Repair": "SelfRepair",
    "Swift Strike": "SwiftStrike",
    "Storm of Steel": "StormOfSteel",
    "Tools of the Trade": "ToolsOfTheTrade",
    "Static Discharge": "StaticDischarge",
    "Strike_Green": "Strike",
    "Strike_Red": "Strike",
    "Strike_Purple": "Strike_P",
    "Strike_Blue": "Strike_B",
    "Defend_Green": "Defend",
    "Steam": "SteamBarrier",
    "Steam Power": "Overclock",
    "Sweeping Beam": "SweepingBeam",
    "ThunderClap": "Thunderclap",
    "ThunderStrike": "Tempest",
    "Through Violence": "ThroughViolence",
    "Thinking Ahead": "ThinkingAhead",
    "The Bomb": "TheBomb",
    "Venomology": "Alchemize",
    "Vengeance": "SimmeringFury",
    "VoidCard": "Void",
    "Well Laid Plans": "WellLaidPlans",
    "Wraith Form v2": "WraithForm",
    "White Noise": "WhiteNoise",
    "Wireheading": "Foresight",
    "Sadistic Nature": "SadisticNature",
}

STARTER_DECK_CARD_IDS: dict[str, list[str]] = {
    "IRONCLAD": [
        "Strike", "Strike", "Strike", "Strike", "Strike",
        "Defend", "Defend", "Defend", "Defend",
        "Bash",
    ],
    "WATCHER": [
        "Strike", "Strike", "Strike", "Strike",
        "Defend", "Defend", "Defend", "Defend",
        "Eruption", "Vigilance",
    ],
    "SILENT": [
        "Strike", "Strike", "Strike", "Strike", "Strike",
        "Defend", "Defend", "Defend", "Defend", "Defend",
        "Neutralize", "Survivor",
    ],
    "DEFECT": [
        "Strike_B", "Strike_B", "Strike_B", "Strike_B",
        "Defend_B", "Defend_B", "Defend_B", "Defend_B",
        "Zap", "Dualcast",
    ],
}


# Backwards-compat alias
IRONCLAD_MIN_DEFS = IRONCLAD_ALL_DEFS
